#!/usr/bin/python3

import json
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed


with open('/home/eugene/nvim/python/rsync_deploy/rs_engine_conf.json') as f:
    sync_data = json.load(f)

EN0_CMD = f'rsync -a --delete {sync_data["local_dir"]} {sync_data["en0"]}'
EN1_CMD = f'rsync -a --delete {sync_data["local_dir"]} {sync_data["en1"]}'


def sync_dirs():
    with ThreadPoolExecutor() as ex:
        futures = (ex.submit(_run_cmd, EN0_CMD), ex.submit(_run_cmd, EN1_CMD))
        for future in as_completed(futures):
            res = future.result()
            if res:
                print(res)


def _run_cmd(cmd: str):
    process = subprocess.run(
        cmd.split(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
        text=True
    )

    return process.stdout


sync_dirs()
