#!/usr/bin/python3

import json
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed


with open('/home/eugene/.config/nvim/python/rsync_deploy/rs_vair_conf.json') as f:
    sync_data = json.load(f)

NODE1 = f'rsync -a --delete {sync_data["local_dir"]} {sync_data["node1"]}'
NODE2 = f'rsync -a --delete {sync_data["local_dir"]} {sync_data["node2"]}'
NODE3 = f'rsync -a --delete {sync_data["local_dir"]} {sync_data["node3"]}'


def sync_dirs():
    with ThreadPoolExecutor() as ex:
        futures = (
            ex.submit(_run_cmd, NODE1),
            ex.submit(_run_cmd, NODE2),
            ex.submit(_run_cmd, NODE3),
        )
        for future in as_completed(futures):
            res = future.result()
            if res:
                print(res)


def _run_cmd(cmd: str):
    process = subprocess.run(
        cmd.split(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
        text=True
    )

    return process.stdout


sync_dirs()
